Initial Home Page Setup Merge to Master
LaunchCodeLiftoffProjects/KC-Water-Garden-App pull request #2
Opened 2020-04-28 01:30 UTC by MulesKC

added HomeController, fragments.html, index.html, styles.css

2020-04-28 01:34 UTC, KBeas21 commented on src/main/resources/templates/index.html
> +                    <a th:href="@{/register}" class="nav-link"><span class="glyphicon glyphicon-user"></span> Register</a>
STUPID LINK NAMENEEDING CHANGES

2020-04-28 01:35 UTC, jamiander commented
Thumbs up!

2020-04-28 01:35 UTC, scottpenneman approved these changes

2020-04-28 01:36 UTC, jamiander approved these changes

2020-04-28 01:36 UTC, hstrodtman approved these changes

2020-04-28 01:36 UTC, KBeas21 approved these changes

2020-04-28 01:42 UTC, KBeas21 requested changes
remove merge conflicts that heather found

2020-04-28 16:15 UTC, KBeas21 commented on README.md
> +- Create user table in MySQL Workbench with one column labeled "id" as a primary key, not null, and auto-incremented.  The rest of the table will populate through persistence when a new user register
Thanks for updating this Jamie!

2020-04-29 01:37 UTC, KBeas21 approved these changes
Ryan and I synced up. These files look good now. We are going to be pushing this to master.

2020-04-29 01:37 UTC, KBeas21 commented on src/main/resources/templates/fragments.html
> +</html>
This </html> needs to be removed as it was duplicated in the rebase (on line 50).

2020-04-29 01:39 UTC, merged